### PR TITLE
T-126: Render: migrate light-volume propagation off CPU-built OccupancyGrid SSBO

### LINKED ISSUE #532: Render: migrate light-volume propagation off CPU-built OccupancyGrid SSBO (T-092 blocker)
## Context

Blocker for T-092 / PR #531. Filed because c_propagate_light_volume still reads the CPU-built occupancy grid SSBO at binding 28 -- which means BUILD_OCCUPANCY_GRID and C_OccupancyGrid cannot be deleted yet.

## Finding

T-072 (Phase 1a/1b/1c, PRs 359/362/360) moved the BFS propagation to GPU but kept the OccupancyGrid SSBO for solidity queries. Every frame:

1. system_build_occupancy_grid.hpp -- CPU walks the full voxel pool and uploads a 256^3 bit-packed grid to OccupancyGridBuffer (SSBO slot 28).
2. system_compute_light_volume.hpp:374-378 -- explicitly rebinds OccupancyGridBuffer to slot 28 before each propagate dispatch.
3. c_propagate_light_volume.glsl:40-68 -- layout(std430, binding = 28) readonly buffer OccupancyGrid; occupancyGetBit() checks it for every neighbor.
4. Metal counterpart: c_propagate_light_volume.metal:32-90 -- same dependency.

Per issue 429: "If the reviewer or the implementing agent finds a hidden consumer that wasn't migrated, that's a bug in T-09X or T-072, not in this task. Bounce it back upstream rather than partially deleting."

## What needs to happen

Remove the OccupancyGrid SSBO read from the propagation shader and the corresponding C_OccupancyGrid component from the COMPUTE_LIGHT_VOLUME system archetype match. Two paths:

1. **Standalone bitfield producer** -- emit a compact voxel-existence SSBO directly from the voxel pool, decoupled from C_OccupancyGrid. The bit-packing and camera-anchor math already live in system_build_occupancy_grid.hpp; the goal is to remove the component so creations do not need setComponent(mainCanvas, C_OccupancyGrid{256}) to light their scenes.
2. **Screen-space proxy** -- replace occupancyGetBit with a trixelDistances or depth-map lookup (long-term direction per engine/render/CLAUDE.md). Higher complexity; out of scope for a targeted unblock.

Path 1 is the pragmatic unblock: move the SSBO producer out of the C_OccupancyGrid component lifecycle so the component can be removed from both the system signature and all creation callsites.

## Affected files

- engine/prefabs/irreden/render/systems/system_compute_light_volume.hpp -- remove C_OccupancyGrid from archetype, use standalone produced SSBO
- engine/render/src/shaders/c_propagate_light_volume.glsl -- remove OccupancyGrid binding, update occupancyGetBit
- engine/render/src/shaders/metal/c_propagate_light_volume.metal -- same
- creations/demos/shape_debug/main.cpp, creations/demos/perf_grid/main.cpp, creations/demos/lighting/common/lighting_demo_scene.hpp -- remove C_OccupancyGrid setComponent and BUILD_OCCUPANCY_GRID registration once decoupled
- engine/prefabs/irreden/render/components/component_occupancy_grid.hpp -- delete after migration
- engine/prefabs/irreden/render/systems/system_build_occupancy_grid.hpp -- delete or slim to standalone producer after migration

## Suggested model

[opus] -- touches render pipeline shader bindings, GPU occupancy source design, and Metal/GLSL backend parity.

## Suggested area

engine/render, engine/prefabs/irreden/render

T-092 (PR 531) is blocked until this lands.

### PR DESCRIPTION
**Pull request by jakildev**
## Summary

T-126 is the pragmatic unblock for T-092: decouple the propagate-shader's slot-28 SSBO from the `C_OccupancyGrid` component lifecycle and rename the SSBO/producer/constants to match the post-T-091 consumer set (only `c_propagate_light_volume` reads the bitfield now; AO migrated to screen-space sampling). The component itself is deleted in this PR — every consumer was already migrated off of it.

## Approach (Path 1)

Pure mechanical rename — slot-28 binding number unchanged, bitfield layout unchanged, the producer still rasterizes voxels + SDF light-blockers into the same parallel bitfields:

- **Shaders:** `OccupancyGrid` block → `LightOcclusionGrid`; `occupancyGetBit` → `voxelOcclusionGetBit`; Metal `OccupancyData` → `LightOcclusionData` (GLSL + Metal kept in lockstep).
- **C++:** `kBufferIndex_OccupancyGrid` → `kBufferIndex_LightOcclusionGrid`; `OccupancyGridHeader` → `LightOcclusionGridHeader`; `BUILD_OCCUPANCY_GRID` → `BUILD_LIGHT_OCCLUSION_GRID`; named resource `"OccupancyGridBuffer"` → `"LightOcclusionGridBuffer"`; file `system_build_occupancy_grid.hpp` → `system_build_light_occlusion_grid.hpp`; perf-timing field/key `buildOccupancyGrid*` → `buildLightOcclusionGrid*`.
- **Producer detached from `C_OccupancyGrid`:** archetype became `<C_VoxelPool, C_TrixelCanvasRenderBehavior>` and the bitfield storage moved into `SystemParams` (was on the per-canvas component). The component is now unreferenced and deleted in this PR.
- **Demos:** `BUILD_LIGHT_OCCLUSION_GRID` registration + include path updated in `shape_debug`, `perf_grid`, `lighting/common/lighting_demo_scene`. `setComponent(mainCanvas, C_OccupancyGrid{256})` removed from all three.
- **Docs:** `engine/render/CLAUDE.md` pipeline diagram + invariants + phased-out producer note refreshed; `.claude/skills/{simplify,review-pr}` and `.claude/agents/review-invariant-render` patterns updated to the new file name.

## Acceptance

- ✅ (1) `c_propagate_light_volume.{glsl,metal}` contain zero reads of `OccupancyGridBuffer`/`occupancyGetBit` (verified via grep)
- ✅ (2) `system_compute_light_volume.hpp` archetype no longer includes `C_OccupancyGrid`
- ✅ (3) Lighting demos build clean (IRLightingCombined/Point/Spot/Emissive/SunShadow + IRShapeDebug + IRPerfGrid). Visual parity expected from the rename-only diff.
- 🟡 (4) `fleet-build` clean on `macos-debug` ✅; `linux-debug` pending cross-host smoke (label `fleet:needs-linux-smoke` — reviewer to add on approval per `engine/render/CLAUDE.md` "Cross-host smoke validation").
- ✅ (5) T-092's hidden-consumer blocker resolved — `C_OccupancyGrid` is fully unused and deleted.

## Test plan

- [x] `fleet-build --target IRShapeDebug` clean on macOS/Metal
- [x] `fleet-build --target IrredenEngineTest` + `./IrredenEngineTest` — 428/428 pass
- [x] `fleet-build --target IRLightingCombined --target IRLightingPoint --target IRLightingSpot --target IRLightingEmissive --target IRLightingSunShadow` clean
- [x] `fleet-build --target IRPerfGrid` clean
- [x] `fleet-run IRShapeDebug --auto-screenshot 10` — all 6 shots captured, no errors
- [ ] Linux/OpenGL smoke via `fleet:needs-linux-smoke` (reviewer adds on approval)

## Visual verification

Skipping `render-debug-loop` and `attach-screenshots` per the `engine/render/CLAUDE.md` "Verifying render changes" exception for **internal refactors with provably no runtime effect**:

- Slot-28 binding number unchanged (`28` literal preserved in both shaders and C++)
- SSBO byte layout unchanged (header + voxel bitfield + blocker bitfield, same offsets)
- Producer algorithm unchanged (same `gridSetBit` + same `rasterizeAllBlockers`)
- Propagate shader algorithm unchanged (same neighbor walk, same bitfield indexing)
- Sun-shadow alias preserved (`kBufferIndex_SunShadowDepthMap = kBufferIndex_LightOcclusionGrid`)

If the reviewer wants screenshot evidence anyway, I'll run the loop on request — flagging here so the absence is intentional and not an oversight.

Closes #532

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Review by jakildev — COMMENTED** [review]
## Review — T-126: Render: migrate light-volume propagation off CPU-built OccupancyGrid SSBO

**Verdict:** approve (Opus recheck required — see below)

### Verification

**Binding parity (slot 28 preserved):**
Both `c_propagate_light_volume.glsl` and `c_propagate_light_volume.metal` still declare `binding = 28` / `[[buffer(28)]]`. `kBufferIndex_LightOcclusionGrid = 28` in `ir_render_types.hpp`. `kBufferIndex_SunShadowDepthMap = kBufferIndex_LightOcclusionGrid` alias preserved. No binding drift. ✓

**SSBO layout unchanged:**
`kLightOcclusionSSBOByteSize = kLightOcclusionHeaderByteSize + 2 * kLightOcclusionBitfieldByteSize` mirrors the old `kOccupancySSBOByteSize` formula exactly. `static_assert(sizeof(LightOcclusionGridHeader) == 16)` preserved. The voxel bitfield offset and blocker bitfield offset (`kLightBlockerBitfieldByteOffset`) are arithmetically identical to the pre-rename constants. ✓

**AO shader fully migrated (acceptance criterion):**
Grepped `c_compute_voxel_ao.glsl` and its Metal counterpart on this branch — zero references to `OccupancyGrid`, `occupancyBits`, or `occupancyGetBit`. T-091 completed the AO migration. The `BUILD_LIGHT_OCCLUSION_GRID` SSBO is now consumed only by `c_propagate_light_volume.{glsl,metal}` as claimed. ✓

**No remaining stale references:**
Full-repo grep for `OccupancyGrid`, `C_OccupancyGrid`, `kBufferIndex_OccupancyGrid`, `OccupancyGridBuffer`, `BUILD_OCCUPANCY_GRID`, `system_build_occupancy_grid` in `.hpp/.cpp/.glsl/.metal` files returns only two hits — both in comments inside `system_build_light_occlusion_grid.hpp` and `ir_render_types.hpp` explaining what was renamed from. No stale code references. ✓

**Archetype changes:**
- `BUILD_LIGHT_OCCLUSION_GRID`: `<C_VoxelPool, C_TrixelCanvasRenderBehavior>` replaces `<C_VoxelPool, C_OccupancyGrid>`. The `useCameraPositionIso_` guard inside the tick correctly identifies the main rendering canvas — same gate `COMPUTE_LIGHT_VOLUME` uses, maintaining coherence. ✓
- `COMPUTE_LIGHT_VOLUME`: `<C_CanvasLightVolume, C_TrixelCanvasRenderBehavior>` replaces `<C_OccupancyGrid, C_CanvasLightVolume, C_TrixelCanvasRenderBehavior>`. The `C_OccupancyGrid` parameter was never used by the tick body (the buffer was looked up from the named resource); its removal is semantically correct. ✓

**`ranThisFrame_` guard:**
Old sentinel: `gridBitfieldData_ = nullptr` reset at end of endTick. New sentinel: `ranThisFrame_ = false` reset at end of endTick. Both are equivalent "did the per-entity tick fire this frame" guards. The endTick early-return on `!p->ranThisFrame_` is correct. ✓

**`voxelBitfield_` lifecycle:**
Allocated once in `create()` (`kLightOcclusionBitfieldUintCount` zeros), cleared via `std::fill` at the start of each tick before population. Replaces the cleared-per-frame `C_OccupancyGrid::bitfield()` vector. ✓

**`gridSetBit` unification:**
`blockerSetBit` → `gridSetBit` now serves both bitfields (same camera-anchored layout, same indexing math). The blocker bitfield continues to be passed as the target in `rasterizeAllBlockers`; the voxel bitfield is passed inline in the tick. Both remain correctly separated in the SSBO upload. ✓

**Named resource lookup sequence:**
`LightOcclusionGridBuffer` is created by `BUILD_LIGHT_OCCLUSION_GRID::create()`. `COMPUTE_LIGHT_VOLUME::create()` looks it up via `getNamedResource<Buffer>("LightOcclusionGridBuffer")` — registration order (BUILD before COMPUTE in every demo pipeline) makes this safe. ✓

**SystemName enum:**
`BUILD_OCCUPANCY_GRID` → `BUILD_LIGHT_OCCLUSION_GRID` in `ir_system_types.hpp` at the correct position. ✓

**GLSL/Metal parity:**
Both shaders updated in lockstep: constants (`kLightOcclusionGridSize/HalfExtent/BitfieldUintCount`), struct name (`LightOcclusionData` in Metal, `LightOcclusionGrid` buffer block in GLSL), function names (`voxelOcclusionGetBit`/`lightBlockerGetBit`), parameter name (`occlusion` for the buffer pointer), and the kernel/main argument (`occlusion [[buffer(28)]]` in Metal). ✓

**Test coverage:**
428/428 pass (PR body). No `C_OccupancyGrid`-specific tests existed; the component was data-only and tested transitively through the lighting demos. ✓

### Nits

- `engine/prefabs/irreden/render/components/component_canvas_fog_of_war.hpp:191-192` — the comment rewrap left `Out-of-range` stranded at the start of a new line after `world-centered cell convention.`, making it read as a sentence fragment on first scan. Minor formatting nit from the word-wrap edit.

### Praise

- Deleting `component_occupancy_grid.hpp` (201 lines) rather than leaving a tombstone or phased-out comment is the right call — the component is unreferenced and the production code is cleaner without it.
- `useCameraPositionIso_` as the main-canvas gate (same filter `COMPUTE_LIGHT_VOLUME` already uses) is a tight coherence invariant. Both producers and the consumer anchor on identical criteria — hard to break separately.
- `ranThisFrame_` bool replacing the raw `const uint32_t *gridBitfieldData_` pointer eliminates the dangling-pointer risk that existed when the pointer pointed into a per-component vector (now that the vector lives in `SystemParams`, lifetime is fine either way, but the flag is cleaner).

### Test plan

- [x] `fleet-build --target IRShapeDebug` clean on macOS/Metal (PR body confirms)
- [x] `IrredenEngineTest` 428/428 pass (PR body confirms)
- [x] Lighting demos (Combined/Point/Spot/Emissive/SunShadow + PerfGrid) build clean (PR body confirms)
- [ ] Linux/OpenGL smoke via `fleet:needs-linux-smoke` (reviewer will add label on this pass)
- [ ] Opus to confirm GPU buffer lifetime and frame-ordering invariants (see below)

Opus recheck required: touches `engine/render/src/shaders/` (both GLSL + Metal propagate compute shaders), `engine/prefabs/irreden/render/systems/system_compute_light_volume.hpp` (GPU buffer rebind per-frame at slot 28, aliased by `kBufferIndex_SunShadowDepthMap`), and `system_build_light_occlusion_grid.hpp` (frame-level SSBO lifetime). Opus to confirm: (1) SSBO slot-28 frame-ordering guarantee — `BUILD_LIGHT_OCCLUSION_GRID` runs and uploads before `COMPUTE_LIGHT_VOLUME` rebinds and dispatches, with no fence needed because the pipeline is single-threaded; (2) `p->occlusionBuf_` pointer from `getNamedResource` at `create()` time is stable for the render manager lifetime (no rehash / reassignment of named resources).

Escalation: please Opus-recheck before merge (touches: engine/render/ shaders, render pipeline GPU buffer lifetime, slot-28 alias).

🤖 Reviewed by Claude Sonnet 4.6 (sonnet-reviewer role)

**Comment by jakildev** [comment]
Addressed nits: merged stranded 'Out-of-range' sentence fragment in component_canvas_fog_of_war.hpp comment (lines 29-31 → 29-30). One-line fix. — sonnet-author

**Review by jakildev — COMMENTED** [review]
## Opus recheck — T-126: light-occlusion SSBO decouple

**Verdict:** approve

Sonnet's first pass already covered binding parity, SSBO byte layout, archetype migration, the `gridSetBit` unification, GLSL/Metal shader lockstep, and the `ranThisFrame_` lifecycle change. Confirming those and focusing this pass on the two invariants Sonnet flagged for Opus recheck.

### Invariant 1 — slot-28 frame ordering (BUILD uploads before COMPUTE reads)

Sonnet asked: "BUILD_LIGHT_OCCLUSION_GRID runs and uploads before COMPUTE_LIGHT_VOLUME rebinds and dispatches, with no fence needed because the pipeline is single-threaded."

**Confirmed.** Walked all three registration sites:

- `creations/demos/lighting/common/lighting_demo_scene.hpp:356` registers `BUILD_LIGHT_OCCLUSION_GRID` before `COMPUTE_LIGHT_VOLUME` (line 363).
- `creations/demos/shape_debug/main.cpp:192` registers BUILD before COMPUTE at line 199.
- `creations/demos/perf_grid/main.cpp:384` registers BUILD before COMPUTE at line 391.

Pipeline execution is sequential per `engine/system/CLAUDE.md`, so BUILD's `endTick` (the `subData` upload at `system_build_light_occlusion_grid.hpp:336-355`) completes before COMPUTE's per-entity tick fires. Between the two, slot 28 is hijacked by `BAKE_SUN_SHADOW_MAP` (writes the sun depth map) and `COMPUTE_SUN_SHADOW` (reads it) — both use `kBufferIndex_SunShadowDepthMap = kBufferIndex_LightOcclusionGrid`. The COMPUTE_LIGHT_VOLUME tick correctly rebinds slot 28 back to `LightOcclusionGridBuffer` at `system_compute_light_volume.hpp:376-381` before the propagate dispatch loop, gated on `lightCount_ > 0`. Pre-T-126 had the identical alias-and-rebind pattern; T-126 preserves it 1:1.

For the host-update→shader-read ordering: OpenGL's command stream guarantees that `glBufferSubData` writes are visible to subsequent dispatch commands without an explicit `MemoryBarrier` (host writes are sequenced at the command-queue level). Same on Metal — buffer-update encoders sequenced on the same `MTLCommandQueue` as subsequent compute encoders. Sonnet's "no fence needed" reasoning is sound.

### Invariant 2 — `p->occlusionBuf_` pointer stability

Sonnet asked: "`p->occlusionBuf_` pointer from getNamedResource at create() time is stable for the render manager lifetime (no rehash / reassignment of named resources)."

**Confirmed.** `engine/render/include/irreden/render/rendering_rm.hpp:85-89` shows `getNamed<T>` looks up the `ResourceId` in `m_namedResources` (`unordered_map<string, ResourceId>`) then calls `get<T>`, which returns `unique_ptr<T>::get()` from `unordered_map<ResourceId, unique_ptr<T>>`. Both maps may rehash on insert, but rehashing only relocates the `unique_ptr` value — the heap-allocated `Buffer` object the `unique_ptr` owns stays put. The `Buffer*` is invalidated only when `destroy<Buffer>(id)` is called, and grepping confirms no path destroys `LightOcclusionGridBuffer` after creation. Pointer is stable for the render manager's lifetime as required.

### Other items I checked while reading the diff

- **No `getComponent` regression.** The new BUILD per-entity tick gets `C_VoxelPool` and `C_TrixelCanvasRenderBehavior` via template parameters; the COMPUTE tick gets `C_CanvasLightVolume + C_TrixelCanvasRenderBehavior`. `rasterizeAllBlockers` uses the batched-archetype-query pattern (no per-entity `getComponent`), matching `cpp-ecs.md`.
- **SystemParams discipline.** `voxelBitfield_` and `blockerBitfield_` live in `Params`, allocated once in `create()`, cleared in-place each frame — no allocations in the hot path.
- **Archetype-gate change.** Previously `<C_VoxelPool, C_OccupancyGrid>` gated BUILD on the component opt-in; now `<C_VoxelPool, C_TrixelCanvasRenderBehavior>` plus a runtime `useCameraPositionIso_` check. The runtime gate matches what `COMPUTE_LIGHT_VOLUME` already used, so producer and consumer are now keyed off the same flag — actually a tighter coherence invariant than the prior split. Multi-canvas safety still relies on the convention "exactly one main canvas has `useCameraPositionIso_=true`", which was already the case for `COMPUTE_LIGHT_VOLUME` pre-T-126.
- **SSBO byte-layout consistency.** Header offset 0 (16 bytes), voxel bits at 16, blocker bits at 16 + 2 MiB. C++ `kLightOcclusionBitfieldUintCount = 524288` matches GLSL/Metal `kLightOcclusionBitfieldUintCount` (256³ / 32 = 524288). The flexible-array-tail trick in the Metal `LightOcclusionData` struct is preserved correctly with the offset shift in `lightBlockerGetBit`.
- **Slot-28 alias intact.** `kBufferIndex_SunShadowDepthMap = kBufferIndex_LightOcclusionGrid` preserved at `ir_render_types.hpp:348`; the doc-comment about T-09Y removing the alias is updated for the rename.
- **Stale references.** Grepped engine sources for `OccupancyGrid`, `C_OccupancyGrid`, `kBufferIndex_OccupancyGrid`, `OccupancyGridBuffer`, `BUILD_OCCUPANCY_GRID`, `system_build_occupancy_grid` — only doc-comments remain (`system_build_light_occlusion_grid.hpp:22,30,226` and `ir_render_types.hpp:334`, all explanatory rename references). `TASKS.md` still references `C_OccupancyGrid` for T-092's tracking, which is appropriate (T-092 deletes the component as a follow-up — actually already done in this PR per the description; the TASKS.md entry may need a follow-up close).

### Diff-vs-master noise (not a finding, just so the human isn't surprised)

`git diff origin/master..HEAD` shows the PR also "deletes" lines from `scripts/fleet/fleet-claim` and `scripts/fleet/fleet-up`. That's an artifact of the branch base — T-126 was cut before T-122/T-123/T-124 landed on master, so master moved forward independently. The merge-base diff (`git diff $(git merge-base origin/master HEAD)..HEAD`) is clean: 19 files, all render-pipeline. GitHub will auto-merge correctly (PR shows `mergeable: MERGEABLE`).

### Nits — defer to Sonnet's pass

Sonnet noted the comment-rewrap awkwardness in `component_canvas_fog_of_war.hpp:184-185` ("Out-of-range" stranded after a wrap). I confirm the diff but it's purely cosmetic. The `fleet:has-nits` label already covers it for the author worker to clean up before merge.

### Verdict

Approve. Both Opus-recheck invariants verified; the rename is mechanically clean; binding/layout/alias all preserved; the new `SystemParams`-owned bitfield storage is a strict improvement over the per-component vector. Cross-host Linux smoke gate (`fleet:needs-linux-smoke`) still outstanding; human merges only after that label clears.

🤖 Reviewed by Claude Opus 4.7 (opus-reviewer role)

**Comment by jakildev** [comment]
Merger: cannot auto-resolve mechanically. The PR has
semantic conflicts with current master that need
judgement-level resolution.

Conflicted files:
- `engine/prefabs/irreden/render/systems/system_compute_light_volume.hpp` — master: `648ef67 T-116: Render: per-canvas light scope via CHILD_OF relation (#541)`; PR: `4e54d1e T-126: rename OccupancyGrid SSBO -> LightOcclusionGrid; drop C_OccupancyGrid`
- `engine/render/CLAUDE.md` — master: `648ef67 T-116: Render: per-canvas light scope via CHILD_OF relation (#541)`; PR: `4e54d1e T-126: rename OccupancyGrid SSBO -> LightOcclusionGrid; drop C_OccupancyGrid`

Labeled `fleet:semantic-conflict` — an opus-worker will
attempt resolution on its next iteration (rebase,
manually resolve, build, push). If the opus-worker also
can't resolve (truly ambiguous, design decision needed),
it will escalate to `human:needs-fix`.

The `fleet:approved` label has been removed if it was set
— the PR no longer represents a reviewed state.

SHA pair: master=55b483a1f7924059979883e6e8b0d38c9385088c × PR=fe0c0d4d15766f7fed6faa5a7a3b2c3c00c20e85

— fleet merger

**Comment by jakildev** [comment]
Resolved semantic conflict against current master. Both files reconciled by preserving T-116's per-canvas light scope (the canvasEntity lambda parameter and the per-canvas-scope CLAUDE.md paragraph) and applying T-126's renames on top:

- `engine/prefabs/irreden/render/systems/system_compute_light_volume.hpp` — kept the `canvasEntity` lambda parameter from master (used by the gather call for per-canvas light scoping) and dropped `C_OccupancyGrid &` from the lambda signature per T-126's intent. Template params are `<C_CanvasLightVolume, C_TrixelCanvasRenderBehavior>`.
- `engine/render/CLAUDE.md` — applied the OccupancyGridBuffer → LightOcclusionGridBuffer / system_build_light_occlusion_grid.hpp renames to the master text while keeping the "without affecting AO" wording and the Per-canvas scope (#363) bullet. Box widths re-aligned to 66 visual columns.

Build clean (`fleet-build --target IRShapeDebug` on macOS). Reviewer please re-evaluate the rebased diff.

— opus-worker

**Review by jakildev — COMMENTED** [review]
## Opus re-review — T-126 (post-merger semantic-conflict resolution)

**Verdict:** needs-fix

### Trigger

The merger force-pushed a semantic-conflict resolution at `4dd97f23` to reconcile this PR with master's T-116 (per-canvas light scope, #541). The merger's resolution comment ("Build clean (`fleet-build --target IRShapeDebug` on macOS)") only built `IRShapeDebug`, which does not transitively include the two files that still reference the deleted `C_OccupancyGrid`. I picked the PR up on the `fleet:changes-made` + render-touching gate.

### Conflict resolution itself — correct

The judgement-call parts of the merge are right:

- `engine/prefabs/irreden/render/systems/system_compute_light_volume.hpp:298-302` — template params reduced to `<C_CanvasLightVolume, C_TrixelCanvasRenderBehavior>` (T-126 dropping the C_OccupancyGrid archetype dep) AND the lambda preserves `EntityId canvasEntity` (T-116's per-canvas scope param). The body at line 330 still threads `canvasEntity` into `gatherLightSources`, so the per-canvas filtering in `gatherLightSources` (line 177: `if (nodeParent != IREntity::kNullEntity && nodeParent != currentCanvas) continue;`) is preserved. ✓
- `engine/render/CLAUDE.md` — both the `OccupancyGridBuffer → LightOcclusionGridBuffer` rename AND the Per-canvas scope (#363) bullet survive. Box widths re-aligned to 66 visual columns. ✓

### Blocker — build is broken on two targets

The merger's resolution deleted `engine/prefabs/irreden/render/components/component_occupancy_grid.hpp` but did not sweep the two non-engine consumers that still include it. Both targets fail to compile on macOS Metal (verified via `fleet-build` from the PR branch in this worktree):

**1. `creations/demos/lighting/main_per_canvas_scope.cpp` (target `IRLightingPerCanvasScope`):**

```
creations/demos/lighting/main_per_canvas_scope.cpp:24:10: fatal error:
    'irreden/render/components/component_occupancy_grid.hpp' file not found
```

This file also constructs `C_OccupancyGrid{256}` at line 41:

```cpp
// TODO(T-126): drop C_OccupancyGrid when T-126 migrates COMPUTE_LIGHT_VOLUME archetype.
EntityId canvasB =
    createEntity(C_OccupancyGrid{256}, C_CanvasLightVolume{}, C_TrixelCanvasRenderBehavior{});
```

The TODO comment names this PR explicitly. The migration this PR ships is exactly the trigger for that cleanup — drop the `#include` at line 24, drop the comment at line 39, and remove `C_OccupancyGrid{256}` from the archetype list at line 41 so it becomes `createEntity(C_CanvasLightVolume{}, C_TrixelCanvasRenderBehavior{})`.

**2. `test/render/per_canvas_light_scope_test.cpp` (target `IrredenEngineTest`):**

```
test/render/per_canvas_light_scope_test.cpp:17:10: fatal error:
    'irreden/render/components/component_occupancy_grid.hpp' file not found
```

The test does not actually construct a `C_OccupancyGrid`; the include is stale. Just remove line 17.

After both fixes, `fleet-build --target IRLightingPerCanvasScope` and `fleet-build --target IrredenEngineTest` should pass — confirmed locally that both compilation units fail only on the deleted-include line.

### Why my prior approval still holds for the rest of the diff

My pre-merger approval (`2026-05-08T17:50:36Z`) covered binding parity, SSBO byte layout, GLSL/Metal lockstep, frame-ordering of BUILD_LIGHT_OCCLUSION_GRID before COMPUTE_LIGHT_VOLUME, and the `getNamedResource` lifetime invariant. The semantic-conflict commit only re-edited two files (`system_compute_light_volume.hpp` body around lines 280–402 and `engine/render/CLAUDE.md` prose) — the rest of the original diff is unchanged. I re-read the full `system_compute_light_volume.hpp` and confirmed the rebase did not regress slot-28 binding (`p->occlusionBuf_->bindBase(... kBufferIndex_LightOcclusionGrid)` at line 398–402) or the `if (p->occlusionBuf_ != nullptr)` guard.

### Followup (no separate PR needed)

The `creations/demos/lighting/main_per_canvas_scope.cpp` TODO is a pre-existing in-tree marker that this PR is the one to clear. Sweep it out as part of the fix push, not as a separate task.

### Test plan

- [ ] Drop `#include <irreden/render/components/component_occupancy_grid.hpp>` from both `creations/demos/lighting/main_per_canvas_scope.cpp` (line 24) and `test/render/per_canvas_light_scope_test.cpp` (line 17).
- [ ] Drop `C_OccupancyGrid{256}` from the `createEntity(...)` call at `main_per_canvas_scope.cpp:41` and remove the now-resolved TODO at line 39.
- [ ] `fleet-build --target IRLightingPerCanvasScope` clean on macOS.
- [ ] `fleet-build --target IrredenEngineTest` clean on macOS; `IrredenEngineTest` runs green.
- [ ] `fleet-build --target IRShapeDebug` re-confirmed clean (already verified by merger).
- [ ] Linux smoke (`fleet:needs-linux-smoke` label) still required after the fix push.

🤖 Reviewed by Claude Opus 4.7 (opus-reviewer role)

**Review by jakildev — COMMENTED** [review]
## Re-review — T-126: Render: migrate light-volume propagation off CPU-built OccupancyGrid SSBO

### Prior-review resolution

- ✅ `component_canvas_fog_of_war.hpp:191-192` — "Out-of-range" stranded as sentence fragment after comment rewrap — verified fixed at ba64630 (author comment confirms the one-line merge, Opus noted as already applied)
- ✅ Opus invariant 1 (slot-28 frame ordering, BUILD uploads before COMPUTE reads) — unchanged by conflict resolution; still correct
- ✅ Opus invariant 2 (occlusionBuf_ pointer stability across render manager lifetime) — unchanged by conflict resolution; still correct

### Conflict-resolution verification

The semantic conflict between T-116 (per-canvas light scope) and T-126 (OccupancyGrid rename) was resolved by the opus-worker. Verified at HEAD:

- `engine/prefabs/irreden/render/systems/system_compute_light_volume.hpp:298-302`: template params are `<C_CanvasLightVolume, C_TrixelCanvasRenderBehavior>` (T-126 drops C_OccupancyGrid); lambda signature includes `const IREntity::EntityId canvasEntity` (T-116's per-canvas scoping preserved). `canvasEntity` is correctly passed to `detail::gatherLightSources()` at lines 328-332. Resolution correct.
- `engine/render/CLAUDE.md:77,86,299`: OccupancyGridBuffer -> LightOcclusionGridBuffer rename applied; Per-canvas scope (#363) bullet from T-116 preserved at line 86. Resolution correct.

### Needs-fix

- `creations/demos/lighting/main_per_canvas_scope.cpp:24,41` — `component_occupancy_grid.hpp` was deleted by this PR but `main_per_canvas_scope.cpp` still includes it (line 24) and instantiates `C_OccupancyGrid{256}` in a `createEntity` call (line 41). `IRLightingPerCanvasScope` will fail to compile. The TODO at line 39 reads "drop C_OccupancyGrid when T-126 migrates COMPUTE_LIGHT_VOLUME archetype" — this PR is that migration; the TODO was never cleared. This file was added by T-116 after T-126's branch was cut and entered the worktree on the rebase without being addressed.

  Fix: remove the `#include <irreden/render/components/component_occupancy_grid.hpp>` line, drop `C_OccupancyGrid{256}` from the `createEntity` call at line 41 (keep `C_CanvasLightVolume{}` and `C_TrixelCanvasRenderBehavior{}`), and remove the now-resolved TODO comment. The PR's test plan built 5 of 14 lighting demo targets and missed `IRLightingPerCanvasScope`; add `--target IRLightingPerCanvasScope` (or `--target IRLightingDemos`) to the build verification before re-requesting review.

**Verdict:** needs-fix

### Test plan the author should run before merge

- [ ] `fleet-build --target IRLightingPerCanvasScope` clean after removing the stale C_OccupancyGrid usage
- [ ] `fleet-build --target IRLightingDemos` clean (all 14 lighting demo targets)

Opus recheck not required — conflict resolution is a pure mechanical merge; no new render pipeline invariants, GPU buffer lifetimes, or ECS structural changes introduced by the rebase. The new finding is a missed file from the post-branch T-116 rebase.

Escalation: author-agent to address, then re-request review.

🤖 Reviewed by Claude Sonnet 4.6 (sonnet-reviewer role)

**Comment by jakildev** [comment]
Addressed Opus re-review feedback (ac127ed):
- Dropped stale include of component_occupancy_grid.hpp from creations/demos/lighting/main_per_canvas_scope.cpp
- Dropped C_OccupancyGrid{256} from the createEntity call and removed the now-resolved TODO comment
- Dropped stale include of component_occupancy_grid.hpp from test/render/per_canvas_light_scope_test.cpp

Builds verified: IRLightingPerCanvasScope (clean), IrredenEngineTest (432/432 pass), IRShapeDebug (clean). fleet:needs-linux-smoke still outstanding.

**Review by jakildev — COMMENTED** [review]
## Re-review — T-126: Render: migrate light-volume propagation off CPU-built OccupancyGrid SSBO

### Needs-fix resolution

Both items from the Sonnet/Opus needs-fix reviews are addressed in commit `ac127ed`:

- ✅ `creations/demos/lighting/main_per_canvas_scope.cpp` — stale `#include <irreden/render/components/component_occupancy_grid.hpp>` removed; `C_OccupancyGrid{256}` dropped from `createEntity(...)` call (now `createEntity(C_CanvasLightVolume{}, C_TrixelCanvasRenderBehavior{})`); now-resolved TODO comment cleared.
- ✅ `test/render/per_canvas_light_scope_test.cpp` — stale `#include <irreden/render/components/component_occupancy_grid.hpp>` removed.

The fix is minimal and exactly correct. Both files introduced by T-116 after T-126's branch was cut now compile cleanly.

### Build verification (from commit message)

- `fleet-build --target IRLightingPerCanvasScope` clean on macOS — the blocking target from the needs-fix now compiles
- `fleet-build --target IrredenEngineTest` 432/432 pass on macOS
- `fleet-build --target IRShapeDebug` clean on macOS (re-confirmed)

### Prior analysis unchanged

All invariants verified in the prior Sonnet and Opus reviews remain valid — the fix commit touches only the two demo/test files; no engine sources were modified:

- Slot-28 binding parity (GLSL + Metal), SSBO byte layout, and alias `kBufferIndex_SunShadowDepthMap = kBufferIndex_LightOcclusionGrid` — unchanged ✓
- Frame-ordering invariant: BUILD_LIGHT_OCCLUSION_GRID uploads before COMPUTE_LIGHT_VOLUME reads — unchanged ✓
- `p->occlusionBuf_` pointer stability across render manager lifetime — unchanged ✓
- No per-entity `getComponent` in tick paths, no allocations in hot loops, no structural changes mid-iteration — unchanged ✓

**Verdict:** approve

Opus recheck not required — the fix is a pure mechanical cleanup of two stale includes/constructor calls. No new render pipeline invariants, GPU buffer lifetimes, or ECS structural changes. Both Opus-recheck invariants were confirmed by the Opus reviewer; the fix commit does not affect them.

Cross-host smoke: `fleet:needs-linux-smoke` already set from the initial review pass; human merges only after that label clears.

🤖 Reviewed by Claude Sonnet 4.6 (sonnet-reviewer role)
